# Generated by Django 5.1.3 on 2024-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
